name: devsecops
on: [push]

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: docker run --rm -v "$PWD:/repo" zricethezav/gitleaks git -v /repo

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: >
          docker run --rm -v "$PWD:/src" -w /src semgrep/semgrep
          semgrep scan --error --config p/owasp-top-ten app.py

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD:/src" aquasec/trivy fs --exit-code 1 --severity CRITICAL /src

  # sbom:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: docker run --rm -v "$PWD:/src" 

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: >
          docker run --rm
          -v "$PWD:/src"
          anchore/syft:latest
          /
          -o cyclonedx-json=/sbom.json

      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  # A compléter pendant l'atelier 2 :
  #  - build de l'image + scan de l'image (Trivy)
  #  - SBOM (Syft) publié comme artefact
  #  - DAST : lancer l'application puis OWASP ZAP baseline sur http://localhost:5000
